# Generated by Django 3.1 on 2021-05-21 12:24

import api.models
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.FileField(upload_to='image/')),
                ('encryption', models.CharField(max_length=40)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_id', models.CharField(max_length=12)),
                ('patient_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('content_date', models.DateField()),
                ('physician_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('actual_class', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('actual_mask', models.FileField(blank=True, null=True, upload_to='actual_mask/')),
                ('predclass', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verify_by', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, default=' ', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.FileField(upload_to=api.models.content_file_name)),
                ('encryption', models.CharField(max_length=40)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_id', models.CharField(max_length=12)),
                ('patient_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('content_date', models.DateField()),
                ('physician_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('actual_class', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('actual_mask', models.FileField(upload_to='actual_mask3D/')),
                ('predclass', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verify_by', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, default=' ', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pipeline_id', models.CharField(blank=True, max_length=40, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_type', models.CharField(choices=[('CLARA', 'CLARA'), ('NON CLARA', 'NON CLARA')], max_length=10)),
                ('description', models.CharField(default='', max_length=500)),
                ('clara_pipeline_name', models.CharField(blank=True, default='empty', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(null=True, upload_to='cover/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('task', models.CharField(choices=[('2D Segmentation', '2D Segmentation'), ('2D Classification', '2D Classification'), ('3D Segmentation', '3D Segmentation'), ('3D Classification', '3D Classification')], max_length=20)),
                ('predclasses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='api.image')),
                ('image3D', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='api.image3d')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='api.pipeline')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='PredictResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.image')),
                ('image3D', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.image3d')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.pipeline')),
            ],
            options={
                'unique_together': {('pipeline', 'image')},
            },
        ),
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='api.project'),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.FileField(upload_to='mask/')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_mask', to='api.predictresult')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image3d',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images3d', to='api.project'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project'),
        ),
        migrations.CreateModel(
            name='Gradcam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradcam', models.FileField(blank=True, null=True, upload_to='imagegrad/')),
                ('predclass', models.CharField(max_length=50)),
                ('predictresult', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradcams', to='api.predictresult')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('pipeline_id', 'model_name')},
        ),
        migrations.AlterUniqueTogether(
            name='image3d',
            unique_together={('project', 'encryption')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('project', 'encryption')},
        ),
    ]
