# Generated by Django 3.0.4 on 2021-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_id',
            field=models.CharField(default='Empty', max_length=40),
        ),
    ]
