# Generated by Django 3.1 on 2021-05-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='netInputname',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='netOutputname',
        ),
    ]
