# Generated by Django 3.0.4 on 2021-01-13 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.FileField(upload_to='image/')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_id', models.CharField(max_length=12)),
                ('patient_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('content_date', models.DateField()),
                ('physician_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='dicoms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='result',
            name='dicoms',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='accuracy',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='api.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.CharField(default='Classification', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='is_verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_id',
            field=models.CharField(default='Empty', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Dicom',
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='api.Project'),
        ),
        migrations.AddField(
            model_name='result',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.Image'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('name',)},
        ),
    ]
