# Generated by Django 3.1 on 2021-02-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='verify_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
