# Generated by Django 3.1 on 2021-02-02 08:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_verify_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictresult',
            name='predicted_polygon',
        ),
        migrations.AddField(
            model_name='predictresult',
            name='predicted_polygon',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), default=[[12, 11]], size=None),
            preserve_default=False,
        ),
    ]
