# Generated by Django 3.1 on 2021-05-15 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210512_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictresult',
            name='gradcam',
        ),
        migrations.CreateModel(
            name='Gradcam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradcam', models.FileField(blank=True, null=True, upload_to='imagegrad/')),
                ('predclass', models.CharField(max_length=50)),
                ('predictresult', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradcams', to='api.predictresult')),
            ],
        ),
    ]
