# Generated by Django 3.0.4 on 2021-01-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210110_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dicoms',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='api.Dicom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pipeline',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='api.Pipeline'),
        ),
    ]
