# Generated by Django 3.0.4 on 2021-01-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210110_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pipeline',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='api.Pipeline'),
        ),
    ]
