# Generated by Django 3.1 on 2021-02-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_queue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='api.image'),
        ),
    ]
