# Generated by Django 3.0.4 on 2021-01-01 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dicom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
