# Generated by Django 3.0.4 on 2021-01-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210115_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='images', to='api.Project'),
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='project',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='pipelines', to='api.Project'),
        ),
    ]
