# Generated by Django 3.1 on 2021-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210206_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.CharField(choices=[('2D Segmentation', '2D Segmentation'), ('2D Classification', '2D Classification'), ('3D Segmentation', '3D Segmentation'), ('3D Classification', '3D Classification')], max_length=20),
        ),
    ]
