# Generated by Django 3.1 on 2021-02-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210206_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='model_name',
            field=models.CharField(default='no name', max_length=50),
        ),
    ]
