# Generated by Django 3.0.4 on 2021-01-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_dicom_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='diag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.Diag'),
        ),
    ]
