# Generated by Django 3.0.4 on 2021-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210119_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ManyToManyField(blank=True, default=None, related_name='images', to='api.Project'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='project',
            field=models.ManyToManyField(blank=True, default=None, related_name='pipelines', to='api.Project'),
        ),
    ]
