# Generated by Django 3.1 on 2021-02-07 06:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pipeline_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='actual_class',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50), size=None),
        ),
        migrations.AlterUniqueTogether(
            name='predictresult',
            unique_together={('pipeline', 'image')},
        ),
    ]
