# Generated by Django 3.0.4 on 2021-01-11 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210110_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dicoms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='dicom',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dicoms', to='api.Project'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='accuracy',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pipelines', to='api.Project'),
        ),
    ]
