# Generated by Django 3.1 on 2021-02-07 07:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210207_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='actual_class',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
