# Generated by Django 3.1 on 2021-02-07 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210207_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='actual_class',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None),
        ),
    ]
