# Generated by Django 3.1 on 2021-02-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210207_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='predclass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
