# Generated by Django 3.1 on 2021-02-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210207_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='note',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
    ]
